### ISSUE TITLE
The image bitmap is always squared! 

### ISSUE THREAD

**Issue by alexodus** [simonsickle/ComposedBarcodes#13]
this code inside this library it's ok only for qrcode, not for 1D-barcode

`
type.getImageBitmap(
                        width = 128 * resolutionFactor,
                        height = 128 * resolutionFactor,
                        value = value
                    )
`

**Comment by simonsickle** [comment]
Thanks for the report! I'm looking at fixing this with version 2 which will be using the native compose canvas and

**Comment by mortenholmgaard** [comment]
Yeah I also having issues with it being a square, which kind of makes in unusable for a CODE_128 barcode.
And also that the background color is white and not transparent (or specifiable)

**Comment by RoyLee-Opsv** [comment]
how about use aspectRatio?

**Comment by NWuensche** [comment]
Seems to be fixed in the current main-branch (with MR #16). Would be nice if one can create a new release on Maven. Would love to help if I somehow can :)

**Comment by georgeherby** [comment]
@simonsickle please you can build a version of main to get the latest functionality from #16 ?

**Comment by simonsickle** [comment]
@georgeherby there are problems with CI it looks like, but I will try to get an updated build released this week time permitting

**Comment by Osanosa** [comment]
any progress update?

**Comment by Osanosa** [comment]
> I would be interested in an update as well 🤔 Is the new version planned anytime soon?

I just did my own encoding function and displaying barcodes as text with . Would wanna publish it as multiplatform library someday 🤤

**Comment by simonsickle** [comment]
Hey all, sorry for the delay here! I haven't had much time to figure out the build tooling issues here to publish a new version of the library.

One of my goals here is to improve performance of the library and use the compose canvas more directly (vs the nativeCanvas). Along with this, I would like to find a new generation library written in Kotlin (or a kotlin only fork of ZXing) to allow multiplatform to work.

This would be a major change and would likely be a v2 


In the mean time, I am planning on getting the tooling / CI fixed so that I can publish an update once again

**Comment by simonsickle** [comment]
1.3.0 has now been released with #16 included.
